# Generated by Django 2.2 on 2019-06-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_readtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(verbose_name='Published at'),
        ),
    ]
